version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: nginx-project-name    
    restart: always
    volumes:
      - ./api:/var/www
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 8000:80
    links:
      - php

  php:
    container_name: php-project-name
    build: ./images/php/
    restart: always
    volumes:
      - ./api:/var/www
    links:
      - db

  db:
    image: mysql:8
    container_name: mysql-project-name
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project-db-name
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/var/database